# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - "1.0"
  - "1.1"
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
install:
  # Obtain MKL from JuliaPackaging
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
        wget https://github.com/JuliaPackaging/Yggdrasil/releases/download/MKL-v2019.0.117/MKL.v2019.0.117.x86_64-linux-gnu.tar.gz &&
        mkdir -p MKL &&
        tar xzf MKL.v2019.0.117.x86_64-linux-gnu.tar.gz -C MKL &&
        export MKLROOT=$(pwd)/MKL &&
        export LD_LIBRARY_PATH="$MKLROOT/lib:$LD_LIBRARY_PATH";
    fi
  - if [ $TRAVIS_OS_NAME = "osx" ]; then
        wget https://github.com/JuliaPackaging/Yggdrasil/releases/download/MKL-v2019.0.117/MKL.v2019.0.117.x86_64-apple-darwin14.tar.gz &&
        mkdir -p MKL &&
        tar xzf MKL.v2019.0.117.x86_64-apple-darwin14.tar.gz -C MKL &&
        export MKLROOT=$(pwd)/MKL &&
        export LD_LIBRARY_PATH="$MKLROOT/lib:$LD_LIBRARY_PATH";
    fi
  - echo MKLROOT="$MKLROOT"
  - echo LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
script:
  - echo MKLROOT="$MKLROOT"
  - echo LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build("GalerkinSparseGrids")'
  - julia -e 'using Pkg; Pkg.test("GalerkinSparseGrids"; coverage=true)';
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GalerkinSparseGrids")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
